router:
  image: yoanisgil/cartero
  links:
    - redis
  environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    HTTP_LISTEN: 0.0.0.0
    HTTP_PORT: 4000
    KUE_UI_LISTEN_PORT: 4001
    KUE_UI_LISTEN_INTERFACE: 0.0.0.0
    ATTEMPTS: 5 # This is the default but it's set here for documentation purposes.
    EMAIL_DELAY: 0.5  # Samve as above
    SERVER_SHUTDOWN_WAIT_TIME: 2 # Samve as above
  ports:
    - 4000:4000
    - 4001:4001
  command: ./node_modules/.bin/nodemon --exec npm run babel-node -- server.js
  volumes:
    - .:/srv/www
worker:
  image: yoanisgil/cartero
  links:
    - redis
  environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    WORKER_SHUTDOWN_WAIT_TIME: 2 # Samve as above
    AWS_FROM_EMAIL: gil.yoanis@gmail.com
    AWS_ACCESS_KEY_ID: AKIAJWUL74IBAVBHHPIQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_REGION: 'us-west-2'
  volumes:
    - .:/srv/www
  command: ./node_modules/.bin/nodemon --exec npm run babel-node -- worker.js
redis:
  image: redis:2.8
npminstall:
  image: yoanisgil/cartero
  command: npm install
  volumes:
    - .:/srv/www
